## Section 0
# Install packages
```{r, slide 17}
install.packages('readr')
install.packages('readxl')
install.packages('tidyr')
install.packages('plyr')
install.packages('dplyr')
install.packages("memisc")
install.packages("car")
install.packages("hunspell")
install.packages("ggplot2")
```
# Library packages
```{r, library packages, slide 18}
library(readr) # Read Tabular data, such as CSV files
library(readxl) # Read excel files
library(tidyr) # Easily Tidy data with 'spread()' and 'gather()' Functions
library(plyr) # Tools for splitting, Applying and Combining data
library(dplyr) # A grammar of data manipulation
```
# Import dataset
```{r, slide 19}
## Method 1 By setting workind directory 
setwd("PASTE R TRAINING FILE FOLDER PATH HERE")
getwd()  # Displays the curent working directory                                   
ACLED_df <- read.csv("ACLED data-2018-04-11-Israel-Palestine.csv") # reading in the ACLED data frame

## Method 2 By inputting the full dirctory path
# ACLED_dftry2 <- read.csv("FULL/Directory/Path")
ACLED_dftry2 <- read.csv("C:/Users/flyff/Desktop/Tesla Gov/R training/ACLED Data-2018-04-11-Israel-Palestine.csv") # reading in the ACLED data frame

identical(ACLED_df,ACLED_dftry2) #This tells you if the two data frames are identifical
```
## Exercise 0
```{r, slide 20}
x <- c(1:10, 1:5, NA)       # c concatenates this list of two ranges 1 through 10 and 1 through 5 and a NA
x
length(x)                   # length of x 
table(x)                    # Frequency counts of entries
max(x, na.rm = TRUE)        # Find the maximum value in x, excluding missing values
min(x, na.rm = TRUE)        # minimum
mean(x, na.rm = TRUE)       # mean
median(x, na.rm = T)        # median 
sum(x, na.rm = T)           # sum
var(x, na.rm = T)           # variance
sd(x, na.rm = T)            # standard deviation

is.na(x)                    # check if each element in x is missing
which(is.na(x))             # the index of missing value in the vector x
which(x == 1)               # the index of a particular value in the vector x
```
## Section 1
# Examing the dataset
```{r, slide 22}
View(ACLED_df)                # To view data (or just click it in the environment)

dim(ACLED_df)                 # Get dimensions - how many observations of how many variables(or just look at the data in the environment)

head(ACLED_df)                # The top few rows of a variable

nrow(ACLED_df)                # number of rows

ncol(ACLED_df)                # number of columns

colnames(ACLED_df)            # name of columns (the variable names) in dataset  
rownames(ACLED_df)            # row names

str(ACLED_df)                 # Compactly displays the structure of an arbitrary R object

unique(ACLED_df$actor1) #See how unique responses you have within a column

library(memisc) # A library containng the codebook function

#checking for empty responses
codebook(as.factor(ACLED_df$year)) # Generates a codebook of a dataset in this case it produces.
# The number and percent of observations that were year 2017 and 2018

codebook(complete.cases(ACLED_df$year)) # Of all the observations which are complete (i.e. have no misisng values)
```
# Subsetting data
```{r, slide 23}
# Subsetting by row and/or column
ACLED_df[1,1]                 # first row first column
ACLED_df[,1]                  # first column
ACLED_df[1,]                  # first row
ACLED_df[,1:2]                # first 2 columns

# Subsetting by variable 
ACLED_df$fatalities           # Only fatalities data

# subsetting by specific criteria
ACLED_df[which(ACLED_df$fatalities > 0),] # Only fatalities data above 0
ACLED_df[which(ACLED_df$source == "Agence France Presse"),] # Only data that has the Agence France Presse source
```
# Summary Report
```{r, slide 24}
# Summary Report Method 1
summary(ACLED_df)                      # Summary of each of the variables
# Summary Report Method 2
aggregate(ACLED_df$fatalities, by= list(ACLED_df$event_type), mean) # The mean of fatalities by event type
```
## Exercise 1
```{r}
# G1 How many fatalities occurred by event type and year?
aggregate(ACLED_df$fatalities, by= list(ACLED_df$year, ACLED_df$event_type), sum)

# G2 Using actor1 how many fatalities were the Unidentified Armed Group (Palestine) involved in?
aggregate(ACLED_df$fatalities, by= list(ACLED_df$actor1), sum)
 
# G3 Which day had the most fatalities?
aggregate(ACLED_df$fatalities, by= list(ACLED_df$event_date), sum)
```
## Section 2
# Recoding with the car package
```{r, slide 27-28}
# library the car package
library(car) # Has the recode function
str(ACLED_dftry2$event_type[1]) #checking what type the first row is
# Replacing event type column with their character counterparts for recoding
ACLED_dftry2$event_type <- as.character(ACLED_dftry2$event_type) 

# Recode Riots/Protests event type to Civil Unrest based on text
ACLED_dftry2$event_type <- recode(ACLED_dftry2$event_type,"'Riots/Protests' = 'Civil Unrest' ")

# Create a new field called New_event_types
ACLED_dftry2$New_event_types <- recode(ACLED_dftry2$event_type,"'Riots/Protests'=Civil Unrest")
```
# Sorting dataset
```{r, slide 29}
## Sorting data
data[order(data$variable), ] # would not change the original data
data.sorted <- data[order(data$var1,data$var2), ] # Sort by two vectors, and save the sorted data in a new data frame
Acled_sorted <- ACLED_df[order(ACLED_df$source, ACLED_df$year), ] # Sort by source and year and save the sorted data into a new data frame
```
## Exercise 2
```{r, slide 30}
# G1 Rename the column "source" to "opinion"
colnames(ACLED_df)[25]<- "opinion"

# G2 Sort the dataset by "opinion" and "year"
Acled_sorted_Ex2 <- ACLED_df[order(ACLED_df$opinion, ACLED_df$year), ] 

# G3 Recode all 'BBC' observations to 'BritishBeingCool'
Acled_sorted_Ex2$opinion<-recode(Acled_sorted_Ex2$opinion,"'BBC'='BritishBeingCool'")
```
## Section 3
# Mispellings/miscategorizations
```{r, slide 32}
library(hunspell)

words <- c("beer", "wiskey", "wine")
# Checks individual words
hunspell_check(words)
 
correct <- hunspell_check(words)
correct # Correct words

# Suggests words for the incorrect bunch of words
hunspell_suggest(words[!correct])

# The hunspell_find function takes a character vector with text (in plain, latex or man format) and returns a list with incorrect words for each line.
bad_words <- hunspell_find("spell checkers are not neccessairy for langauge ninja's")
print(bad_words)

# Finally hunspell_suggest is used to suggest correct alternatives for each (incorrect) input word.
hunspell_suggest(bad_words[[1]])

# Arabic example
ar <- dictionary("C:/Users/flyff/AppData/Local/RStudio-Desktop/dictionaries/languages-user/ar.dic")
library(readxl) # read in excel and xlsx files
Arabic_df <-  read_excel("C:/Users/flyff/Desktop/Tesla Gov/R training/Cleaned STACSY-ACLED Data.xlsx")
codebook(hunspell_check(Arabic_df$description_arabic,dict = ar))
abrabic_des <- hunspell_find(Arabic_df$description_arabic,dict = ar)
str(bad_words[[1]])
hunspell_suggest(abrabic_des[2],dict = ar)
```
## Section 4
# Merging data frames
```{r, 36}
ACLED_df_2 <- read.csv("C:/Users/flyff/Desktop/Tesla Gov/R training/2018-04-12-2018-08-01-Middle_East-Israel-Palestine.csv") # A second data set of ACLED data
str(ACLED_df_2)
# rbind() merges the two data frames by colnames
Merged_ACLED_df<- rbind(ACLED_df,ACLED_df_2) # merging the two ACLED data sets
Merged_ACLED_df
```
# Plotting data
```{r}
library(ggplot2)
# Barplot, Good.
barplot(table(Merged_ACLED_df$event_type), xlab = "Event Type", ylab = "Frequency")
title(main = list("Frequency of Events via Merged ACLED data", font = 4))
# Histogram, Better.
ggplot (ACLED_df, aes(x=fatalities,fill = event_type ))   +   		geom_histogram ()
# Hisogram with more arguments, Best.
ggplot (ACLED_df, aes(x=fatalities,fill = event_type ))   +   		geom_histogram (position = "dodge", color = "white", binwidth = 1) 
# Even better than the tbest
ggplot (ACLED_df[ACLED_df$fatalities<2,], aes(x=fatalities,fill = event_type ))   +   		geom_histogram (position = "dodge", color = "white", binwidth = 1) 
# Plot of the summary data

Merged_ACLED_agg <- aggregate(Merged_ACLED_df$fatalities, by=list(Merged_ACLED_df$event_type, Merged_ACLED_df$country), mean)

ggplot(Merged_ACLED_agg, aes(x=Group.2, y= x, fill = Group.1)) + 
  geom_bar(position = "dodge", stat="identity", color = "white")+
  labs( title = "Fatalities by Area",
        subtitle = " ",
        caption = " ",
        x = "Country",
        y = "Fatalities",
        fill = "Event Type")
```
## Section 5
## Multiple linear regression
```{r}
# A summary of the multiple linear regression of fatalities on country and event type
summary(lm(fatalities~country + event_type, Merged_ACLED_df)) 
```
#Country codes
```{r}
# install.packages(countrycode)
library(countrycode) #Convert Country names and Country codes
countrycode(c('USA', 'DZA'), 'iso3c', 'cown')
countrycode('Albania', 'country.name', 'iso3c')
countrycode('Albanien', 'country.name.de', 'iso.name.fr')
```
